import fs from "fs";
import path from "path";
import pdf from "pdf-parse/lib/pdf-parse.js";

async function generate() {
  const dataDir = "./data";
  const outputFile = "./rag_docs.js";

  console.log("Reading PDFs from data directory...");
  const files = fs.readdirSync(dataDir).filter(file => file.endsWith(".pdf"));

  const docs = [];

  for (const file of files) {
    const filePath = path.join(dataDir, file);
    console.log(`Parsing ${file}...`);
    const dataBuffer = fs.readFileSync(filePath);
    try {
      const data = await pdf(dataBuffer);
      // Clean up text content a bit (remove multiple spaces and clean line breaks)
      const cleanText = data.text
        .replace(/\r\n/g, "\n")
        .replace(/\n{3,}/g, "\n\n")
        .replace(/[ \t]+/g, " ")
        .trim();

      docs.push({
        title: file,
        content: cleanText
      });
      console.log(`Successfully parsed ${file} (${cleanText.length} characters)`);
    } catch (err) {
      console.error(`Error parsing ${file}:`, err);
    }
  }

  // Generate the client-side JavaScript content
  const jsContent = `// This file is auto-generated by generate_rag.js. Do not edit manually.
// It contains the extracted text from the PDFs in the data folder.

const RAG_DOCS = ${JSON.stringify(docs, null, 2)};

if (typeof window !== "undefined") {
  window.RAG_DOCS = RAG_DOCS;
}
`;

  fs.writeFileSync(outputFile, jsContent, "utf8");
  console.log(`Successfully wrote extracted text to ${outputFile}`);
}

generate().catch(console.error);
